### register
curl -X 'POST' \
  'http://localhost:8081/api/v2/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "root",
  "password": "1234",
  "level": "normal"
}'

### login
curl -X 'POST' \
  'http://localhost:8081/api/v2/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234"  
}'


### add product
curl -X 'POST' \
  'http://localhost:8081/api/v2/product/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'id=&name=test&price=11&stock=33'