### register
curl -X 'POST' \
  'http://localhost:8081/api/v2/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "root",
  "password": "1234",
  "level": "normal"
}'

### login
curl -X 'POST' \
  'http://localhost:8081/api/v2/login' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "admin",
  "password": "1234"  
}'


### add product
# curl -X 'POST' \
#   'http://localhost:8081/api/v2/product/' \
#   -H 'accept: application/json' \
#   -H 'Content-Type: application/x-www-form-urlencoded' \
#   -d 'id=&name=test2&price=211&stock=233'

### add product using curl (support only in terminal)
curl -X 'POST' \
'http://localhost:8081/api/v2/product/' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'image=@test.jpg;type=image/jpeg' \
-F 'name=test2' \
-F 'price=232' \
-F 'stock=34'

### update product using curl (support only in terminal)
curl -X 'PUT' \
'http://localhost:8081/api/v2/product/' \
-H 'accept: application/json' \
-H 'Content-Type: multipart/form-data' \
-F 'id=3' \
-F 'image=@test2.jpg;type=image/jpeg' \
-F 'name=test3' \
-F 'price=100' \
-F 'stock=200'

### query all products
curl -X 'GET' \
  'http://localhost:8081/api/v2/product/' \
  -H 'accept: application/json'

### query product by id
curl -X 'GET' \
  'http://localhost:8081/api/v2/product/2' \
  -H 'accept: application/json'

### delete product by id
curl -X 'DELETE' \
  'http://localhost:8081/api/v2/product/4' \
  -H 'accept: application/json'


### add transaction
curl -X 'POST' \
  'http://localhost:8081/api/v2/transaction/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "total": 0,
  "paid": 0,
  "change": 0,
  "payment_type": "cash",
  "payment_detail": "none",
  "order_list": "[]",
  "staff_id": "admin"
}'